#!/usr/bin/env bash
# EMULATOR ONLY. Write SYNTHETIC CPUUtilization datapoints for the W5 instance.
# Emulated instances do not run, so Moto has no real CPU data for them.
# Dry run by default. Pass --confirm to write the datapoints.
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/lib.sh"
parse_confirm "$@"

if [[ "$MODE" != "emulator" ]]; then
  echo "Refusing to run: AWS_ENDPOINT_URL is not set. Synthetic metrics are for the emulator only;" >&2
  echo "real AWS collects real CPUUtilization for the W5 instance." >&2
  exit 1
fi

NAMESPACE="${METRIC_NAMESPACE:-AWS/EC2}"
HOURS="${METRIC_HOURS:-24}"
PERIOD_MIN=5

# shellcheck disable=SC2046
INSTANCE="$(aws_ ec2 describe-instances --filters $(tag_filters W5) \
  "Name=instance-state-name,Values=pending,running" \
  --query 'Reservations[0].Instances[0].InstanceId' --output text)"
if [[ "$INSTANCE" == "None" ]]; then
  echo "W5 instance not found in the emulator - apply the lab first." >&2
  exit 1
fi
POINTS=$((HOURS * 60 / PERIOD_MIN))

banner "Inject idle CPU metrics"
echo
echo "Metric source: SYNTHETIC (generated by this script, not measured)"
echo "Plan: write $POINTS CPUUtilization datapoints (one per $PERIOD_MIN min, last $HOURS h, 0.2-1.5 %)"
echo "      namespace $NAMESPACE, dimension InstanceId=$INSTANCE"

if [[ "$CONFIRM" -ne 1 ]]; then
  echo
  echo "Dry run only. Re-run with --confirm to write the datapoints."
  exit 0
fi

# Written in files of 50 datapoints each: Moto rejects larger requests.
chunk_dir="$(mktemp -d)"
trap 'rm -rf "$chunk_dir"' EXIT
python3 - "$INSTANCE" "$POINTS" "$PERIOD_MIN" "$chunk_dir" <<'PY'
import datetime, json, random, sys

instance, points, period, out = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
random.seed(5)
now = datetime.datetime.now(datetime.timezone.utc).replace(second=0, microsecond=0)
data = [
    {
        "MetricName": "CPUUtilization",
        "Dimensions": [{"Name": "InstanceId", "Value": instance}],
        "Timestamp": (now - datetime.timedelta(minutes=period * n)).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "Value": round(random.uniform(0.2, 1.5), 3),
        "Unit": "Percent",
    }
    for n in range(points)
]
for i in range(0, len(data), 50):
    with open("%s/chunk-%04d.json" % (out, i), "w") as f:
        json.dump(data[i:i + 50], f)
PY

for chunk in "$chunk_dir"/chunk-*.json; do
  aws_ cloudwatch put-metric-data --namespace "$NAMESPACE" --metric-data "file://$chunk"
done
echo
echo "Wrote $POINTS SYNTHETIC CPUUtilization datapoints for $INSTANCE to $NAMESPACE."
