// Writes src/fonts.ts from the font files the landing page serves, so the
// HTML report is set in the same typefaces without fetching anything.
// Run it when a file in site/fonts changes: npm run fonts
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const fonts = join(here, "../../../site/fonts");
const faces = [
  ["ARCHIVO", "archivo-latin-variable.woff2"],
  ["COURIER_PRIME_400", "courier-prime-latin-400.woff2"],
  ["COURIER_PRIME_700", "courier-prime-latin-700.woff2"],
];

const lines = [
  "/**",
  " * The report's typefaces as base64 WOFF2, so the one file needs nothing else.",
  " * Archivo and Courier Prime are under the SIL Open Font License; the licence",
  " * texts ship in this package's licenses directory.",
  " *",
  " * Generated by scripts/embed-fonts.mjs from site/fonts. Do not edit by hand.",
  " */",
  ...faces.map(([name, file]) => `export const ${name} = "${readFileSync(join(fonts, file)).toString("base64")}";`),
  "",
];
writeFileSync(join(here, "../src/fonts.ts"), lines.join("\n"));
for (const licence of ["OFL-Archivo.txt", "OFL-CourierPrime.txt"]) copyFileSync(join(fonts, licence), join(here, "../licenses", licence));
console.log("Wrote src/fonts.ts and licenses/");
